---
title: "pilot_a_writeup"
author: "Erik Santoro"
date: "November 19, 2017"
output: 
  html_document:
  toc: true
---

------

#### Overview

Replication of Study 4 by Sample & Sample (2015, Journal of Experimental Psychology: General)

#### Changes to Make For Pilot B

* Stimuli

* Measures
    
* Attenion Check
    + Add an attention check? I am not sure what the best attention check is to add

* Variable naming
    + Add flowers time & DV 

------

#Introduction

------

#Methods

##Power Analysis

The original authors used a MANOVA when looking at one outcome variable (the number of trials completed) and two factors each with two levels (role model -- past or future self; task -- fun or self-control). With the consultation with Ian, we decided to do a two-way ANOVA.

For effect size, I converted a partial eta squared value 0.05 (I used the eta squared value reported in the paper of 0.05, which we can assume are the same) to cohen's f using G*Power. I used alpha = 0.001 as they found a signifance less than 0.001. I used a total sample size of 224. The numerator DF was 1 (per paper; also (2-1) times (2-1) for a two way anova). And the number of groups is 4.


##Planned Sample

##Materials

##Procedure

##Analysis Plan
	**Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.**  

**Overview:**

There are two confirmatory replicaiton analyses. The first confirmatory analysis is to replicate the significant interaction by task and role model. The second confirmatory analysis is to replicate the finding that the interaction was still signficant after adding the three covariates (difficulty imainging self, the level of detail of the self, and the distance from the self). 

Importantly, whereas the original paper used a MANOVA to look at the interaction between the two categorical factors, task (fun or self-control) and role model (past or future self), on the number of trials completed, we decided to use a two-way ANOVA as there is only one dependent variable not two (see here for reference: http://www.statsmakemecry.com/smmctheblog/stats-soup-anova-ancova-manova-mancova).

**Relevant Excerpts from Paper:**

One participant reported confusion because the photos did not load properly. Excluding this participant does not meaningfully affect the results, so the entire sample was retained. Data were submitted to a univariate MANOVA, with Task and Role Model as fixed factors. Number of trials completed before quitting was the dependent variable.

... Importantly, this effect was qualified by a predicted interaction with role model, F(1, 220) = 12.45, p < .001, eta squared = .05 (see Figure 3). For the fun version of the task, participants motivated by their past self completed more trials (M = 6.90, SD = 3.57) than did participants motivated by their future self (M = 5.03, SD = 3.43), F(1, 220) = 9.95, p = .002, eta squared = .04. However, for the self-control version of the task, future-motivated participants (M = 4.63, SD = 2.97) completed more trials than past-motivated participants (M = 3.45, SD = 2.74), F(1, 220) = 3.52, p = .06, eta squared = .016.

... Importantly, when entering these items as covariates in the model, all results were essentially identical: The critical interaction remained significant, F(1, 217) = 11.45, p = .001, eta squared = .05, as did the reported contrasts for the fun task, F(1, 217) = 8.98, p = .003, eta squared = .04, and for the self-control task, F(1, 217) = 3.35, p = .068, eta squared = .015.


**Analysis Steps**


1) Exclusion: No exclusion of participants, unless there is confusion over the procedures

2) Data Cleaning: Summarize the data so that for each participant, their task (fun or self-control), role model (past or future self), number of trials completed (need to summarize), and their responses for the three covariates (difficulty, detail, distance) are included. The number of trials will be a range from 0 to 10, and is equal to the number of times the participant selected the option "show me another one"; as O'Brien (2015) notes, this is equal to the number of photos the participant viewed *before* choosing to end the slideshow.

3) Analysis: Conduct a two-way anova such that find the main effect of task, the main effect of role model, and the interaction between the two on the number of trials. Then, conduct the same two-way anova separately for each of the three covariates: difficulty, detail, and distance.


##Differences from Original Study

###Sample differences

###Setting differences

###Procedure differences

— New questions: manipulation check (did you keep it in mind) & mediator (distance during task); modified other mediator (distance now)

— Added time

— Put demographics at end
— Added “I prefer another term” for gender
— Added an education question
— Did not randomize question order for demo's

- For future, wrote "who you imagine being" rather than "recall being"

###Analysis plan differences

------

#Methods Addendum (Post Data Collection)

##Actual Sample Size

##Differences from pre-data collection methods plan

------

#Results

##Data preparation

### Step 1: Load packages

[Some useful packages are being loaded below. You can add any additional ones you might need too.]

```{r}
library(tidyverse) # for data munging
library(knitr) # for kable table formating
library(ggthemes)
```

### Step 2: Load data

```{r Load file}

d <- read_csv("data/obrien2015_pilotA_November 14, 2017_10.54.csv")


```

```{r Clean & Filter data}

#Filter out first two rows
d <- d %>%
  filter(!((IPAddress == "IP Address") |
           IPAddress == "{\"ImportId\":\"ipAddress\"}")) %>% #need the backlash to view the quote
  select(contains("DV"), condition, ResponseId, difficult, detailed, farawaynow)


```


### Step 3: Tidy data

```{r Tidy data}


#Tidy data

d.tidy <- d %>%
  gather(dv, dvresponse, contains("DV")) %>%
  filter(!is.na(dvresponse)) %>% #filters out n/a responses ; to be tidy, we could modify the dv repsonse label to clean up
  mutate(rolemodel = ifelse(condition == "pastrational","past",
                            ifelse(condition =="pastfun","past","future"))) %>%
  mutate(task = ifelse(condition == "pastrational","selfcontrol",
                            ifelse(condition =="futurerational","selfcontrol","fun"))) 
    

#Make dv response into a numeric

d.tidy$dvresponse <- as.numeric(d.tidy$dvresponse)

#Summarize by task

d.wide <- d.tidy %>%
  group_by(ResponseId, task, rolemodel, difficult, detailed, farawaynow) %>%
  summarise(numtrials = sum(dvresponse == 1, na.rm = TRUE))
 
#Convert task & rolemodel & covariates to factor

d.wide$task <- as.factor(d.wide$task)
d.wide$rolemodel <- as.factor(d.wide$rolemodel)
d.wide$difficult <- as.factor(d.wide$difficult)
d.wide$detailed <- as.factor(d.wide$detailed)
d.wide$distancenow <- as.factor(d.wide$farawaynow)


#Make 
d.wide$numtrials <- as.numeric(d.wide$numtrials)


```

##Confirmatory analysis


```{r Two-Way ANOVA for Num Trials}


#Reference: https://www.r-bloggers.com/r-tutorial-series-two-way-anova-with-pairwise-comparisons/
#Note that this doesn't analysis doesn't yield anything as there is only 1 data point per group; error: "ANOVA F-tests on an essentially perfect fit are unreliable"


fit <- anova(lm(numtrials ~ task * rolemodel, d.wide))

#fyi, these are the same: aov(numtrials ~ task * rolemodel, d.summarized)

fit

```


```{r Two-Way ANOVA for Num Trials with Covariates}

fit.difficult.covariate <- anova(lm(numtrials ~ task * rolemodel + difficult , d.wide))
fit.detailed.covariate <- anova(lm(numtrials ~ task * rolemodel + detailed, d.wide))
fit.distancenow.covariate <- anova(lm(numtrials ~ task * rolemodel + distancenow, d.wide))

fit.difficult.covariate
fit.detailed.covariate
fit.distancenow.covariate

```



##Exploratory analysis



------

#Discussion

##Summary of Replication Attempt

##Commentary



